apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - astarte.yaml
patches:
  # This patch is set by the Astarte Setup script
  - path: kustomize-astarte-patch.yaml
    target:
      group: api.astarte-platform.org
      kind: Astarte
      name: astarte
      version: v2alpha1
