name: Test

on:
  pull_request:
  push:

jobs:
  deploy-astarte-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create Astarte cluster
        id: create-astarte-cluster
        uses: ./
        with:
          astarte_version: "1.3-snapshot"
          astarte_realm: "customrealm"
          astarte_namespace: "astarte-test-namespace"
      - name: Test cluster functionality (register a device)
        run: |
          astartectl config current-context
          astartectl config contexts show $(astartectl config current-context)
          export DEVICE_ID=$(astartectl utils device-id generate-random)
          astartectl pairing agent register -- $DEVICE_ID
